projects:
  frontend:
    schema:
      - './frontend/client.schema.graphql'
      - './frontend/schema.graphql'
    documents: './frontend/**/*.graphql'
  backend:
    include:
      - './backend/schema-directives.graphql'
      - './backend/programmatic-types.graphql'
      - './backend/graphql/**/*.graphql'
    schema: './backend/graphql/schema.graphql'
