packages:
  - frontend
  - backend
  - mobile

catalog:
  '@typescript/native': npm:typescript@^7.0.2
  typescript: ~6.0.3

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - shell-quote@1.10.0

overrides:
  fast-uri: 3.1.2
  lightningcss: 1.30.1
  shell-quote: 1.10.0
packageExtensions:
  '@react-native-google-signin/google-signin@*':
    dependencies:
      '@expo/config-plugins': '*'
