import './index.css'

import type { Metadata, Viewport } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import type { ReactNode } from 'react'

import { AppNavigation } from '~/shared/components/AppNavigation'
import { AppProviders } from '~/shared/providers/AppProviders'
import { CsrfProvider } from '~/shared/providers/CsrfProvider'
import { TransitionsProvider } from '~/shared/providers/TransitionsProvider'

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
})

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
})

export const viewport: Viewport = {
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  themeColor: '#F7F7F8',
  viewportFit: 'cover',
  width: 'device-width',
}

export const metadata: Metadata = {
  appleWebApp: {
    statusBarStyle: 'black-translucent',
  },
  description: 'Generated by @liinkiing/larastack.',
  title: {
    default: 'Larastack',
    template: '%s | Larastack',
  },
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html className={`${geistSans.variable} ${geistMono.variable}`} lang="en">
      <body>
        <CsrfProvider>
          <AppProviders>
            <AppNavigation />
            <TransitionsProvider>{children}</TransitionsProvider>
          </AppProviders>
        </CsrfProvider>
      </body>
    </html>
  )
}
